apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: akshay-namespace
  project: akshay-2
spec:
  artifact:
    path:
      name: file://akshay-namespace/akshay-namespace.yaml
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: akshay-learning
    - key: rafay.dev/clusterName
      value: akshay-mks-aws
  resourceQuotas: {}
